version: 2

builds:
  - id: rmgedcomx
    main: ./cmd/server
    binary: rmgedcomx
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENCE
      - royal92.rmtree
      - gedcomx_browser.py

release:
  github:
    owner: aviast
    name: rmgedcomx
