version: 2

builds:
  - id: rmgedcomx
    main: ./cmd/server
    binary: rmgedcomx
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]

release:
  github:
    owner: aviast
    name: rmgedcomx
